# modules/stock_lists_updated.py

# ✅ NIFTY 50 (as of Sept 2025)
nifty50 = [
    "ADANIPORTS.NS","APOLLOHOSP.NS","ASIANPAINT.NS","AXISBANK.NS","BAJAJ-AUTO.NS",
    "BAJFINANCE.NS","BAJAJFINSV.NS","BEL.NS","BHARTIARTL.NS","BPCL.NS",
    "CIPLA.NS","COALINDIA.NS","DRREDDY.NS","EICHERMOT.NS","GRASIM.NS",
    "HCLTECH.NS","HDFCBANK.NS","HDFCLIFE.NS","HINDALCO.NS","HINDUNILVR.NS",
    "ICICIBANK.NS","INDIGO.NS","INFY.NS","ITC.NS","JIOFIN.NS",
    "JSWSTEEL.NS","KOTAKBANK.NS","LT.NS","M&M.NS","MARUTI.NS",
    "MAXHEALTH.NS","NESTLEIND.NS","NTPC.NS","ONGC.NS","POWERGRID.NS",
    "RELIANCE.NS","SBILIFE.NS","SBIN.NS","SHRIRAMFIN.NS","SUNPHARMA.NS",
    "TATACONSUM.NS","TATAMOTORS.NS","TATASTEEL.NS","TCS.NS","TECHM.NS",
    "TITAN.NS","TRENT.NS","ULTRACEMCO.NS","UPL.NS","WIPRO.NS"
]

# ✅ NIFTY Next 50 (as of Sept 2025, unique from NIFTY 50)
other50 = [
    "ADANIENT.NS","ADANIGREEN.NS","ADANIPOWER.NS","AMBUJACEM.NS","AUROPHARMA.NS",
    "AUBANK.NS","BANKBARODA.NS","BERGEPAINT.NS","BIOCON.NS","BRITANNIA.NS",
    "CANBK.NS","CHOLAFIN.NS","CUMMINSIND.NS","DABUR.NS","DIVISLAB.NS",
    "DLF.NS","GAIL.NS","GODREJCP.NS","HAVELLS.NS","ICICIGI.NS",
    "ICICIPRULI.NS","IDFCFIRSTB.NS","INDUSINDBK.NS","IOC.NS","IRFC.NS",
    "JINDALSTEL.NS","JSWENERGY.NS","LICI.NS","LTIM.NS","MCDOWELL-N.NS",
    "NMDC.NS","OFSS.NS","PEL.NS","PIDILITIND.NS","PNB.NS",
    "RECLTD.NS","SIEMENS.NS","SRF.NS","TATACHEM.NS","TATAPOWER.NS",
    "TORNTPHARM.NS","TVSMOTOR.NS","UBL.NS","VBL.NS","VEDL.NS",
    "VOLTAS.NS","PAYTM.NS","ZEEL.NS","BANDHANBNK.NS","SHREECEM.NS"
]

# ✅ Combined and deduplicated (should total exactly 100 unique stocks)
all_stocks = sorted(list(set(nifty50 + other50)))


